name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # (development build)
      - name: Build for (development)
        run: pnpm build --mode development

      - name: Deploy development
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:development
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Clean dist before next build
      - name: Clean dist folder
        run: rm -rf dist

      # (production build)
      - name: Build for (production)
        run: pnpm build --mode production

      - name: Deploy production
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
